### ISSUE TITLE
Org repository does not show up on individual dashboard

### ISSUE THREAD

**Issue by cresslank** [sage-ai-dev/sage-issues#2]
If you add an organization repository as part of the new user flow, it will successfully be added and indexed, but then it will not show up on your individual dashboard after indexing. Additionally, you then cannot add more repositories as an individual (since on the settings page you are locked into the org dropdown option -- individual account does not appear).

Edit: figured out that I could go back through the new user flow to install the app individually as well.

(I scheduled time on Thursday -- excited to talk more)

**Comment by akhilmurthy** [comment]
Hey, looking forward to meeting. You should be able to access your org repos by clicking the account dropdown in the banner. Your orgs that you are a part of will show up there as long as there are successfully indexed repos for that org. 

To get your personal account to show up on the settings page, you will have to install the GitHub app for your user account as well. Once it is installed, you should be able to see all the repos for your personal user account and kick off indexing jobs. Here's the link to the app page: https://github.com/apps/sage-ai-app

Let me know if you still have any issues, we can look into any other concerns on our call on Thursday too.

**Comment by cresslank** [comment]
![image](https://github.com/sage-ai-dev/sage-issues/assets/9219265/640f223c-b7ac-4763-ae62-90eaa65442f8)

Yep will install on my personal account. As you can see on the drop down there's no way to select the org? Maybe I'm misunderstanding.

**Comment by cresslank** [comment]
![image](https://github.com/sage-ai-dev/sage-issues/assets/9219265/a31d617f-a996-4ec7-b600-72b4f6e964c6)

And here you can see in my settings that the org repository is successfully indexed, and now that I've configured the app for my personal repositories I can select from the dropdown there. It still doesn't let me see the org repository in the dashboard (and there's no org in the dropdown in the dashboard)

**Comment by akhilmurthy** [comment]
Is the current GitHub user that you are logged in as a part of the Organization? If you are a part of the org, the dropdown in the dashboard should show the Corner-3-Partners org

**Comment by cresslank** [comment]
![image](https://github.com/sage-ai-dev/sage-issues/assets/9219265/d703c763-2b6b-4d65-8a95-0aa027941673)

Yes current user is part of that organization

**Comment by cresslank** [comment]
Is it possibly an issue that I configured the app with the organization first, and added an org repo first?

**Comment by akhilmurthy** [comment]
I don't believe the order should be an issue. If you could, would you be able to show me the network tab in your browser developer tools for the "user/org" request? The headers as well as the response if possible.

**Comment by akhilmurthy** [comment]
After doing a bit of research, I believe the issue is related to the permissions of your GitHub organization. When I try and retrieve the orgs for your user account (both public and private memberships) via api, I get an empty response. 

There might be something in your organization's settings that is restricting access. You can go to your org settings and go to  OAuth Application Policy and see whether our oauth application has been approved by your org.

**Comment by cresslank** [comment]
that did the trick! thanks
